[tool.poetry]
name = "splashcat"
version = "0.1.0"
description = ""
authors = ["kitt <catgirl@catgirlin.space>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
Django = "^4.2"
django-htmx = "^1.14"
django-allauth = "^0.54"
django-debug-toolbar = "^4.1"
channels = "^4.0"
daphne = "^4.0"
pillow = "^9.5.0"
msgpack = "^1.0.5"
jsonschema = "^4.17.3"
docutils = "^0.20"
requests = "^2.31.0"
python-dateutil = "^2.8.2"
sentry-sdk = "^1.24.0"
django-crispy-forms = "^2.0"
crispy-tailwind = "^0.5.0"
python-dotenv = "^1.0.0"
dj-database-url = "^2.0.0"
psycopg2-binary = "^2.9.6"
celery = { extras = ["redis"], version = "^5.2.7" }
django-celery-results = "^2.5.1"
django-celery-beat = "^2.5.0"
boto3 = "^1.26.147"
django-anymail = { extras = ["postmark"], version = "^10.0" }
django-storages = "^1.13.2"
eventlet = "^0.33.3"
django-unicorn = "^0.51.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
