[tool.poetry]
name = "splashcat"
version = "0.1.0"
description = ""
authors = ["kitt <catgirl@catgirlin.space>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
Django = "^4.2"
django-htmx = "^1.14"
django-allauth = "^0.54"
django-debug-toolbar = "^4.0"
channels = "^4.0"
daphne = "^4.0"
pillow = "^9.5.0"
msgpack = "^1.0.5"
jsonschema = "^4.17.3"
docutils = "^0.19"
requests = "^2.29.0"
python-dateutil = "^2.8.2"
sentry-sdk = "^1.21.1"
django-crispy-forms = "^2.0"
crispy-tailwind = "^0.5.0"
python-dotenv = "^1.0.0"
dj-database-url = "^2.0.0"
psycopg2-binary = "^2.9.6"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
